### ISSUE TITLE
Add API allowing shorter more expressive layout code

### ISSUE THREAD

**Issue by tbuschto** [eclipsesource/tabris-js#1677]
### Problem description

A continuous pain point in our development seems to be cluttered and verbose layout code. Partially this can be fixed with better practices (particularly in our older code), but overall the layout API we have is not flexible enough to create short and expressive layouts. Note that it is not an issue of certain layouts being impossible to achieve, it's just often impracticable.

### Expected behavior

There are a number of measure that could improve the situation.
 - [ ] ~~Implementing https://github.com/eclipsesource/tabris-js/issues/1674~~ - *No longer in scope*
 - [x] Allow new shorthand for box dimensions and allow using them to set `padding`:  `[<top>, <right>, <bottom>, <left>]` 
 - New property aliases :
   - [ ] ~~`position = [<left>, <top>] | 'left top' ` as shorthand for setting left and top~~
   - [ ] ~~`center = [<x>, <y>] | 'x y'` as shorthand for setting centerX and centerY~~
   - [ ]  ~~`size = [<width>, <height>] | 'width height' ` as shorthand for setting width and height~~
   - [ ] ~~`stretchX`/`stretchY` for left/right and top/bottom (useful for Column/Row layouts)~~
   - [ ] ~~Some of these could also support the single-value shorthand, e,g, `center = 0` is `centerX = 0` and `centerY = 0`~~ - *We now have `fill` and `center` as valid values of `layoutData`, that takes care of most of the same use cases*
  - [x] Allow boolean (`true`) for centerX/centerY, possibly also some or all other layoutData values to set useful non-auto defaults in JSX
 - [x] New `excludeFromLayout` property, see https://github.com/eclipsesource/tabris-js/issues/226
 - [x] Value `'auto'` as an alias for `null` (more expressive, can be used in strings)
 - [ ] ~~More powerful `prev()`/`next()` expressions. Allow giving a number or selector parameter. This would often eliminate the need for assigning an id to a widget only to be able to reference it in a layout.~~ - *Referencing something by an offset is a bad idea, very unstable*
 - [ ] ~~New selectors, see https://github.com/eclipsesource/tabris-js/issues/1678~~ - *Out of scope, we should try to focus less on selectors as they are not TypeScript friendly*
 - [x] Create components such as `Row`, `Column` (creating composites) or `RowLayout`, `ColumnLayout` (creating widget collections). - *Created issue #1823 for row* 

### Environment

Any.

### Code snippet

Something like this could be the result:

![image](https://user-images.githubusercontent.com/527303/41466051-c8aafa5a-70a0-11e8-92e9-9b134c58f520.png)

**Comment by tbuschto** [comment]
All done
